### ISSUE TITLE
Horizontal Scaling - Many to One Issue

### ISSUE THREAD

**Issue by K4r1it0** [trickest/resolvers#6]
I am using this wordlist (9m) https://wordlists-cdn.assetnote.io/data/manual/best-dns-wordlist.txt with puredns (Horizontal Scaling - Many to One). on 100 instances. The wordlist is splitted 9m/100 instance = 95k for each instance this 95k takes 20 sec with puredns on my digitalocean VPS but when I run it using axiom the execution time is +10m I expected the execution time to be -1m since axiom executes all puredns instances in same time is this intended?
```
[{
    "command":"/home/op/go/bin/puredns bruteforce input  --resolvers /home/op/resolvers.txt | tee output",
    "ext":"txt",
}]
```

**Comment by mhmdiaa** [comment]
Hi @K4r1it0,

It sounds like this issue is related to axiom specifically and doesn't have much to do with the resolvers project. You will probably have better luck asking your question [there](https://github.com/pry0cc/axiom/issues). I hope you find the answer, and feel free to reopen this ticket with more details if you think the issue is caused by the resolvers list.

P.S. This is an obvious plug, but I use the same wordlist often on Trickest and it's pretty straightforward to scale the machines there with pretty good execution times. Check out https://trickest.com if you're interested (nothing against axiom though; it's an awesome project!)
